Display version at the top of every command (#127)
This will make it so a user knows what version of cwms-cli they are
using

I have placed it just below the "usage" line in the help page

Tested with `--version` and `--version` to see if a missing version
would be replaced with the output

> Error: No such option: --versio Did you mean --version?

But got another traceback. Resolved that in a commit referencing the PR.